<?php

namespace App\Models;

use App\Enums\AliasType;
use Illuminate\Database\Eloquent\Model;

class Alias extends Model
{
    protected  $table = 'alias';

    protected  $guarded = ['id'];

    public function findModel($type, $id = null){

        switch ($id){
            case null:
                switch ($type){
                    case AliasType::PRODUCT_CATEGORY:
                        return new CategoryProduct();
                        break;
                    case AliasType::PRODUCT:
                        return new Product();
                        break;
                    case AliasType::NEWS_CATEGORY:
                        return new NewsCategory();
                        break;
                    case AliasType::NEWS:
                        return new News();
                        break;
                    case AliasType::PAGES:
                        return new Pages();
                        break;
                    case AliasType::VIDEO:
                        return new Videos();
                        break;
                    case AliasType::GALLERY:
                        return new Gallery();
                        break;
                }
                break;
                default;
                    switch ($type){
                        case AliasType::PRODUCT_CATEGORY:
                            return CategoryProduct::find($id);
                            break;
                        case AliasType::PRODUCT:
                            return Product::find($id);
                            break;
                        case AliasType::NEWS_CATEGORY:
                            return NewsCategory::find($id);
                            break;
                        case AliasType::NEWS:
                            return News::find($id);
                            break;
                        case AliasType::PAGES:
                            return Pages::find($id);
                            break;
                        case AliasType::VIDEO:
                            return Videos::find($id);
                            break;
                        case AliasType::GALLERY:
                            return Gallery::find($id);
                            break;
                    }
        }
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }
}
