<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AttributeCategory extends Model
{
    protected $table = 'attribute_categorys';

    protected $guarded = ['id'];

    public function attributes(){

        return $this->hasMany(Attribute::class,'category_id');
    }

    public function scopePublic($q){
        $q->wherePublic(1);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($category){
            $category->attributes()->delete();
        });
    }
}
