<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    protected $guarded = ['id'];

    public function category(){
        return $this->belongsTo(AttributeCategory::class);
    }

//    public function products(){
//        return $this->hasMany();
//    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($attribute){

        });
    }
}
