<?php

namespace App\Models;

use App\Enums\ProductSessionType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Cart;

class Import extends Model
{
    protected $guarded = ['id'];

    public function agency(){
        return $this->belongsTo(UserAgency::class,'agency_id');
    }

    public function sessions(){
        return $this->hasMany(ProductSession::class)->whereType(ProductSessionType::getKey(ProductSessionType::import));
    }

    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($import){
//            foreach(Cart::content() as $cart):
//
//                $session = ProductSession::create([
//                    'import_id' => $import->id,
//                    'agency_id' => $import->agency_id,
//                    'user_create' => Auth::id(),
//                    'product_id' => $cart->id,
//                    'amount' => $cart->qty,
//                    'price_in' => $cart->price,
//                    'type' => ProductSessionType::getKey(ProductSessionType::import)
//                ]);
//
//            //update số lượng sản phẩm được nhập
//            $amount = $session->product->amount;
//            $amount = $amount + $cart->qty;
//            $session->product()->update(['amount' => $amount]);
//            endforeach;
//
//            //update công nợ của nhà cung cấp
//            $debt = $import->agency->debt;
//            $debt = $debt + $import->debt;
//
//            $import->agency()->update(['debt' => $debt]);
//
//            Cart::destroy();
        });
    }
}
