<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Photo extends Model
{
    protected $guarded = [];

    public function product(){
        return $this->belongsTo(Product::class,'type_id')->whereType($this->type);
    }

    public function scopePublic($q){
        $q->wherePublic(1);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function($photo){
            $photo->user_id = $photo->user_id ? $photo->user_id : auth()->id();
            $photo->lang = $photo->lang ? $photo->lang : session()->get('lang');
        });
        self::deleting(function($photo){
            if(File::exists($photo->image))
                File::delete($photo->image);

            if (File::exists($photo->thumb))
                File::delete($photo->thumb);
        });
    }
}
