<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected  $guarded = ['id'];

    public function lang(){
        $this->belongsTo(Lang::class,'lang', 'value');
    }

    public function scopeLangs($q){
        $q->whereLang(session()->get('lang'));
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
